# Generated by Django 3.0.5 on 2020-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablename',
            old_name='ex_email',
            new_name='email_address',
        ),
    ]
