# Generated by Django 3.0.5 on 2020-04-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0002_auto_20200416_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablename',
            old_name='column_name',
            new_name='password',
        ),
    ]
