# Generated by Django 3.0.5 on 2020-04-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0003_auto_20200416_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablename',
            old_name='password',
            new_name='pass_word',
        ),
    ]
