# Generated by Django 3.0.5 on 2020-04-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0005_auto_20200427_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logintable',
        ),
    ]
