# Generated by Django 3.0.5 on 2020-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0008_auto_20200502_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetable',
            name='institute_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetable',
            name='institute_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetable',
            name='institute_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
