# Generated by Django 3.0.5 on 2020-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0010_auto_20200503_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetable',
            name='experience',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
